import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/form";
import HeroForm from "../components/heroForm";
import SvgFrom from "../components/svg/form";

const Home: NextPage = () => {
  return (
    <div className="grid 2xl:grid-cols-2">
      <Head>
        <title>Login Form</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-screen bg-gray-200">
        <span className="detal"></span>
        <span className="detal-2"></span>
        <HeroForm />
      </div>
      <div className="relative h-screen background">
        <Form />
        <SvgFrom className="absolute md:w-[700px]  bottom-0 -z-50" />
      </div>
    </div>
  );
};

export default Home;
